ALTER TABLE players
  ADD COLUMN IF NOT EXISTS birthdate DATE NULL,
  ADD COLUMN IF NOT EXISTS show_kids TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS show_teen TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS show_adult TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS country VARCHAR(2) NULL;
