-- Word of the Day entries for Search & Play
-- Run: mysql -u root -p games_dictionary < web/word_of_day_seed.sql

INSERT IGNORE INTO word_of_day (date, word, english_word, definition, synonyms, antonyms) VALUES
('2026-03-25', 'αγάπη', 'Love', 'The deepest form of love and affection in Greek culture, often used to describe unconditional love.', 'έρωτας, στοργή', 'μίσος'),
('2026-03-26', 'σοφία', 'Wisdom', 'The quality of having experience, knowledge, and good judgment; one of the cardinal virtues in Greek philosophy.', 'γνώση, φρόνηση', 'αφροσύνη'),
('2026-03-27', 'ελευθερία', 'Freedom', 'The power or right to act, speak, or think as one wants without hindrance or restraint.', 'ανεξαρτησία, αυτονομία', 'δουλεία'),
('2026-03-28', 'δύναμη', 'Power', 'Physical or mental strength and energy; the ability to do something or act in a particular way.', 'ισχύς, κράτος', 'αδυναμία'),
('2026-03-29', 'ειρήνη', 'Peace', 'Freedom from disturbance; tranquility. A state of harmony between people or groups.', 'γαλήνη, ησυχία', 'πόλεμος'),
('2026-03-30', 'θάρρος', 'Courage', 'The ability to do something that frightens one; bravery in the face of danger or difficulty.', 'ανδρεία, τόλμη', 'δειλία'),
('2026-03-31', 'αλήθεια', 'Truth', 'The quality or state of being true; that which is in accordance with fact or reality.', 'πραγματικότητα, ειλικρίνεια', 'ψέμα'),
('2026-04-01', 'ομορφιά', 'Beauty', 'A combination of qualities that pleases the aesthetic senses, especially the sight.', 'κάλλος, χάρη', 'ασχήμια'),
('2026-04-02', 'φιλία', 'Friendship', 'A relationship of mutual affection between people; one of the greatest virtues in Aristotelian ethics.', 'αδελφοσύνη, συντροφιά', 'εχθρότητα'),
('2026-04-03', 'γνώση', 'Knowledge', 'Facts, information, and skills acquired through experience or education; the theoretical understanding of a subject.', 'σοφία, μάθηση', 'άγνοια'),
('2026-04-04', 'χαρά', 'Joy', 'A feeling of great pleasure and happiness; one of the most positive human emotions.', 'ευτυχία, αγαλλίαση', 'λύπη'),
('2026-04-05', 'ψυχή', 'Soul', 'The spiritual or immaterial part of a human being; the essence of a person in Greek philosophy.', 'πνεύμα, νους', NULL),
('2026-04-06', 'ήρωας', 'Hero', 'A person who is admired for their courage, outstanding achievements, or noble qualities.', 'παλικάρι, γενναίος', 'δειλός'),
('2026-04-07', 'φως', 'Light', 'The natural agent that stimulates sight and makes things visible; a symbol of knowledge and truth in Greek thought.', 'λάμψη, φεγγοβολιά', 'σκοτάδι'),
('2026-04-08', 'θάλασσα', 'Sea', 'The expanse of salt water that covers most of the earth''s surface; central to Greek civilization and mythology.', 'πέλαγος, ωκεανός', NULL),
('2026-04-09', 'μουσική', 'Music', 'Vocal or instrumental sounds combined to produce beauty of form, harmony, and expression of emotion.', 'μελωδία, αρμονία', NULL),
('2026-04-10', 'λόγος', 'Word/Reason', 'In Greek philosophy, the principle of reason and judgment; also means word, speech, or discourse.', 'νους, λόγια', NULL),
('2026-04-11', 'κόσμος', 'World/Order', 'The universe or world; in Greek, it also means order and beauty — the opposite of chaos.', 'σύμπαν, τάξη', 'χάος'),
('2026-04-12', 'χρόνος', 'Time', 'The indefinite continued progress of existence and events in the past, present, and future.', 'καιρός, εποχή', NULL),
('2026-04-13', 'νίκη', 'Victory', 'An act of defeating an enemy or opponent in a battle, game, or other competition.', 'επιτυχία, θρίαμβος', 'ήττα'),
('2026-04-14', 'αρετή', 'Virtue', 'Behavior showing high moral standards; in Greek ethics, excellence of character and mind.', 'ηθική, αξία', 'κακία'),
('2026-04-15', 'πόλεμος', 'War', 'A state of armed conflict between different nations or states or different groups within a nation.', 'μάχη, σύγκρουση', 'ειρήνη'),
('2026-04-16', 'φύση', 'Nature', 'The phenomena of the physical world collectively, including plants, animals, the landscape, and other features.', 'περιβάλλον, κόσμος', NULL),
('2026-04-17', 'τέχνη', 'Art', 'The expression or application of human creative skill and imagination; in Greek, also means craft or skill.', 'δημιουργία, έργο', NULL),
('2026-04-18', 'δικαιοσύνη', 'Justice', 'Just behaviour or treatment; the quality of being fair and reasonable; a cardinal virtue in Greek philosophy.', 'ισότητα, δίκαιο', 'αδικία'),
('2026-04-19', 'ζωή', 'Life', 'The condition that distinguishes animals and plants from inorganic matter; the existence of an individual.', 'βίος, ύπαρξη', 'θάνατος'),
('2026-04-20', 'θεός', 'God', 'A superhuman being or spirit worshipped as having power over nature or human fortunes; central to Greek religion.', 'θεότητα, δαίμονας', NULL),
('2026-04-21', 'ήλιος', 'Sun', 'The star around which the earth orbits; worshipped as the god Helios in ancient Greek religion.', 'φως, αστέρι', NULL),
('2026-04-22', 'γη', 'Earth', 'The planet on which we live; in Greek mythology, Gaia is the personification of the Earth.', 'χώμα, πλανήτης', NULL),
('2026-04-23', 'νερό', 'Water', 'A colorless, transparent, odorless liquid; one of the four classical elements in ancient Greek philosophy.', 'υγρό, πηγή', NULL);
